/* ──────────────────────────────────────────────────────────
   MapuaInventory  –  full setup + seed  (PC 00-40 only)
   ────────────────────────────────────────────────────────── */

-- 1. Recreate the database
DROP DATABASE IF EXISTS `MapuaInventory`;
CREATE DATABASE `MapuaInventory`
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;
USE `MapuaInventory`;

-- 2. Room table
CREATE TABLE `Room` (
  `RoomID` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`RoomID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 3. Computers table (add 'Defective' to enum)
CREATE TABLE `Computers` (
  `RoomID`     VARCHAR(10) NOT NULL,
  `PCNumber`   CHAR(2)     NOT NULL COMMENT '00-40 students; 41 instructor',
  `Status`     ENUM('Available','In Use','Maintenance','Retired','Defective')
                 NOT NULL DEFAULT 'Available',
  `LastUpdated` DATE NOT NULL DEFAULT (CURRENT_DATE),
  PRIMARY KEY (`RoomID`,`PCNumber`),
  FOREIGN KEY (`RoomID`) REFERENCES `Room`(`RoomID`)
      ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 4. Insert one room
INSERT INTO `Room` VALUES ('MPO310');

-- 5. Seed student PCs 00-40
INSERT INTO `Computers` (RoomID, PCNumber)
SELECT 'MPO310', LPAD(n,2,'0')
FROM (
  SELECT  0 n UNION ALL SELECT  1 UNION ALL SELECT  2 UNION ALL SELECT  3 UNION ALL
  SELECT  4     UNION ALL SELECT  5 UNION ALL SELECT  6 UNION ALL SELECT  7 UNION ALL
  SELECT  8     UNION ALL SELECT  9 UNION ALL SELECT 10 UNION ALL SELECT 11 UNION ALL
  SELECT 12     UNION ALL SELECT 13 UNION ALL SELECT 14 UNION ALL SELECT 15 UNION ALL
  SELECT 16     UNION ALL SELECT 17 UNION ALL SELECT 18 UNION ALL SELECT 19 UNION ALL
  SELECT 20     UNION ALL SELECT 21 UNION ALL SELECT 22 UNION ALL SELECT 23 UNION ALL
  SELECT 24     UNION ALL SELECT 25 UNION ALL SELECT 26 UNION ALL SELECT 27 UNION ALL
  SELECT 28     UNION ALL SELECT 29 UNION ALL SELECT 30 UNION ALL SELECT 31 UNION ALL
  SELECT 32     UNION ALL SELECT 33 UNION ALL SELECT 34 UNION ALL SELECT 35 UNION ALL
  SELECT 36     UNION ALL SELECT 37 UNION ALL SELECT 38 UNION ALL SELECT 39 UNION ALL
  SELECT 40
) AS nums;

-- 6. Instructor PC 41 (optional – not used by layout logic)
INSERT INTO `Computers` VALUES ('MPO310','41','Available',CURDATE());

-- 7. Daily status log
CREATE TABLE `ComputerStatusLog` (
  `RoomID`    VARCHAR(10) NOT NULL,
  `PCNumber`  CHAR(2)     NOT NULL,
  `CheckDate` DATE        NOT NULL,
  `Status`    ENUM('Working','Defective') NOT NULL,
  PRIMARY KEY (`RoomID`,`PCNumber`,`CheckDate`),
  FOREIGN KEY (`RoomID`,`PCNumber`)
      REFERENCES `Computers`(`RoomID`,`PCNumber`)
      ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 8. Seed YESTERDAY & TODAY as Working (PC 00-40 only)
INSERT INTO `ComputerStatusLog` (RoomID, PCNumber, CheckDate, Status)
SELECT 'MPO310', LPAD(n,2,'0'), CURDATE() - INTERVAL 1 DAY, 'Working'
FROM (SELECT  0 n UNION ALL SELECT  1 UNION ALL SELECT  2 UNION ALL SELECT  3 UNION ALL
      SELECT  4 UNION ALL SELECT  5 UNION ALL SELECT  6 UNION ALL SELECT  7 UNION ALL
      SELECT  8 UNION ALL SELECT  9 UNION ALL SELECT 10 UNION ALL SELECT 11 UNION ALL
      SELECT 12 UNION ALL SELECT 13 UNION ALL SELECT 14 UNION ALL SELECT 15 UNION ALL
      SELECT 16 UNION ALL SELECT 17 UNION ALL SELECT 18 UNION ALL SELECT 19 UNION ALL
      SELECT 20 UNION ALL SELECT 21 UNION ALL SELECT 22 UNION ALL SELECT 23 UNION ALL
      SELECT 24 UNION ALL SELECT 25 UNION ALL SELECT 26 UNION ALL SELECT 27 UNION ALL
      SELECT 28 UNION ALL SELECT 29 UNION ALL SELECT 30 UNION ALL SELECT 31 UNION ALL
      SELECT 32 UNION ALL SELECT 33 UNION ALL SELECT 34 UNION ALL SELECT 35 UNION ALL
      SELECT 36 UNION ALL SELECT 37 UNION ALL SELECT 38 UNION ALL SELECT 39 UNION ALL
      SELECT 40) AS nums;

INSERT INTO `ComputerStatusLog` (RoomID, PCNumber, CheckDate, Status)
SELECT 'MPO310', LPAD(n,2,'0'), CURDATE(), 'Working'
FROM (SELECT  0 n UNION ALL SELECT  1 UNION ALL SELECT  2 UNION ALL SELECT  3 UNION ALL
      SELECT  4 UNION ALL SELECT  5 UNION ALL SELECT  6 UNION ALL SELECT  7 UNION ALL
      SELECT  8 UNION ALL SELECT  9 UNION ALL SELECT 10 UNION ALL SELECT 11 UNION ALL
      SELECT 12 UNION ALL SELECT 13 UNION ALL SELECT 14 UNION ALL SELECT 15 UNION ALL
      SELECT 16 UNION ALL SELECT 17 UNION ALL SELECT 18 UNION ALL SELECT 19 UNION ALL
      SELECT 20 UNION ALL SELECT 21 UNION ALL SELECT 22 UNION ALL SELECT 23 UNION ALL
      SELECT 24 UNION ALL SELECT 25 UNION ALL SELECT 26 UNION ALL SELECT 27 UNION ALL
      SELECT 28 UNION ALL SELECT 29 UNION ALL SELECT 30 UNION ALL SELECT 31 UNION ALL
      SELECT 32 UNION ALL SELECT 33 UNION ALL SELECT 34 UNION ALL SELECT 35 UNION ALL
      SELECT 36 UNION ALL SELECT 37 UNION ALL SELECT 38 UNION ALL SELECT 39 UNION ALL
      SELECT 40) AS nums;

-- 9. Trigger (add AFTER seeding to avoid overlap error)
DELIMITER $$
CREATE TRIGGER trg_sync_computer_status
AFTER INSERT ON ComputerStatusLog
FOR EACH ROW
BEGIN
  UPDATE Computers
     SET Status      = IF(NEW.Status='Defective','Defective','Available'),
         LastUpdated = CURDATE()
   WHERE RoomID   = NEW.RoomID
     AND PCNumber = NEW.PCNumber;
END$$
DELIMITER ;

-- 10. Quick pivot check: Yesterday vs Today
SELECT
  c.PCNumber,
  logY.Status AS Yesterday,
  logT.Status AS Today
FROM ( SELECT PCNumber FROM Computers WHERE RoomID='MPO310' AND PCNumber <='40' ) c
LEFT JOIN ComputerStatusLog logY
       ON logY.RoomID='MPO310' AND logY.PCNumber=c.PCNumber
      AND logY.CheckDate = CURDATE()-INTERVAL 1 DAY
LEFT JOIN ComputerStatusLog logT
       ON logT.RoomID='MPO310' AND logT.PCNumber=c.PCNumber
      AND logT.CheckDate = CURDATE()
ORDER BY CAST(c.PCNumber AS UNSIGNED);
